#' combine_reg() combine estimates from mitools like objects
#'
#' @param mi_estimates is an object generated by mitools::mitools::MIcombine or survey::withPV()
#'
#' @return a tidy table with estimates, estandard errors, p value, and confidence intervals
#'
#' @examples
#' library(dplyr)
#' library(erce)
#' ## add example besides combine_reg()
#'
#'
#' @export
# function
combine_reg <- function(mi_estimates) {

  require(dplyr)
  require(mitools)

  mi_results <- mitools::MIcombine(mi_estimates)
  summary    <- summary(mi_results)
  tidy_results <- summary %>%
    tibble::rownames_to_column("term") %>%
    dplyr::rename(e = results,
                  se = se,
                  lo = `(lower`,
                  hi = `upper)`) %>%
    cbind(miss_info = mi_results$missinfo) %>%
    cbind(df = mi_results$df) %>%
    dplyr::mutate(p_val = 2 * (1 - pt(abs(e / se), df))) %>%
    dplyr::mutate(
      e = as.numeric(e),
      se = as.numeric(se),
      p_val = as.numeric(p_val),
      lo = as.numeric(lo),
      hi = as.numeric(hi),
      miss_info = as.numeric(miss_info)
    ) %>%
    dplyr::select(term, e, se, p_val, lo, hi) %>%
    tibble::as_tibble()

  return(tidy_results)

  # Source: https://github.com/wepelham3/sack2/blob/master/R/tidy_MIcombine.R

}
